""
" Imposta dimensione tabulazione
set tabstop=2
set shiftwidth=2
set expandtab
set nu

""
" Comando per aprire nuovo tab
command! -complete=file -nargs=1 T tabedit <args>

""
" Muoversi fra tab con H (sinistra) e L (destra)
nnoremap H gT
nnoremap L gt

""
" Aggiunge automaticamente indentazione su nuova riga
set autoindent

""
" Evidenzia risultati ricerca
set hlsearch

""
" Mostra opzioni sopra la linea di comando
set wildmenu

""
" Evidenziazione sintassi ItalianRuby
syntax on

highlight italianRubyKeyword              ctermfg=171
highlight italianRubyDefinitionKeyword    ctermfg=171
highlight italianRubySpecial              ctermfg=33
highlight italianRubySpecialBoolean       ctermfg=33
highlight italianRubyMethod               ctermfg=220
highlight italianRubyMethodName           ctermfg=220
highlight italianRubySymbol               ctermfg=33
highlight italianRubyNumeric              ctermfg=148
highlight italianRubySplatOperator        ctermfg=117
highlight italianRubyInstanceVar          ctermfg=117
highlight italianRubyInterpolationStart   ctermfg=117
highlight italianRubyInterpolationStop    ctermfg=117
highlight italianRubyConstant             ctermfg=43
highlight italianRubyComment              ctermfg=28
highlight italianRubyString               ctermfg=208
