set tabstop=2
set shiftwidth=2
set expandtab
set nu

syntax on

highlight italianRubyKeyword              ctermfg=171
highlight italianRubyDefinitionKeyword    ctermfg=171
highlight italianRubySpecial              ctermfg=33
highlight italianRubyMethod               ctermfg=220
highlight italianRubyMethodName           ctermfg=220
highlight italianRubySymbol               ctermfg=33
highlight italianRubySplatOperator        ctermfg=33
highlight italianRubyInstanceVar          ctermfg=117
highlight italianRubyConstant             ctermfg=43
highlight italianRubyComment              ctermfg=28
highlight italianRubyString               ctermfg=208
