# frozen_string_literal: true

require_relative "alias/array"
require_relative "alias/class"
require_relative "alias/date"
require_relative "alias/enumerator"
require_relative "alias/error"
require_relative "alias/false_class"
require_relative "alias/file"
require_relative "alias/float"
require_relative "alias/hash"
require_relative "alias/integer"
require_relative "alias/kernel"
require_relative "alias/main"
require_relative "alias/module"
require_relative "alias/nil_class"
require_relative "alias/numeric"
require_relative "alias/object"
require_relative "alias/open_struct"
require_relative "alias/proc"
require_relative "alias/range"
require_relative "alias/rational"
require_relative "alias/symbol"
require_relative "alias/stdin"
require_relative "alias/string"
require_relative "alias/time"
require_relative "alias/true_class"
